## Project information
site_name: Regolamento unico dei controlli interni del comune di Palermo
site_url: https://rtd-comemipiace.readthedocs.io/it/latest/
site_description: Regolamento unico dei controlli interni del comune di Palermo
site_author: comune di Palermo

## Repository
repo_url: https://github.com/cirospat/regolamento-controlli-interni-comunepalermo
repo_name: regolamento-controlli-interni-comunepalermo
edit_uri: edit/master/docs/

theme:
  name: "material"
  logo: images/palermologo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: it
  features:
    - navigation.top
  icon:
     repo: fontawesome/brands/github
  
  
  
nav:
  - Home: README.md
  - CAPO I - disposizioni generali: capo1.md
  - CAPO II - il controllo interno di regolarità amministrayiva e contabile: capo2.md
  - CAPO III - il controllo strategico: capo3.md
  - CAPO IV - il controllo di gestione: capo4.md
  - CAPO V - il controllo sulla qualità dei servizi erogati: capo5.md
  - CAPO VI - il controllo sulle società partecipate non quotate: capo6.md
  - CAPO VII - il controllo sugli equilibri finanziari: capo7.md
  - CAPO VIII - risultanze dai controlli e disposizioni finali: capo8.md
  - Privacy: 
    - Privacy: privacy.md


plugins:
- search
- mkdocstrings


# Extensions
markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- footnotes
- attr_list
- def_list 
- pymdownx.inlinehilite
  

## Social Media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ComunePalermo
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cirospat/regolamento-controlli-interni-comunepalermo
    - icon: fontawesome/solid/envelope
      link: mailto:protocollo@cert.comune.palermo.it
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/regolamento-unico-controlli-interni-comunepalermo/
  
## setting dal progetto originale https://github.com/up42/up42-py/blob/master/mkdocs.yml + https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

## copiright
copyright: <a href="https://twitter.com/ComunePalermo" title="Comune di Palermo " target="_blank">Comune di Palermo </a> | 2021 | CC BY 4.0 Int Licence
